sudo: required
services: 
  - docker

before_install:
  - docker build -t thotesonali6/react-test -f ./client/Dockerfile.dev .

script:
  - docker run -e CI=true thotesonali6/react-test npm test

after_success:
  - docker build -t thotesonali6/multi-client ./client
  - docker build -t thotesonali6/multi-nginx ./nginx
  - docker build -t thotesonali6/multi-server ./server
  - docker build -t thotesonali6/multi-worker ./worker
  # log in to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take these images and push those to docker hub
  - docker push thotesonali6/multi-client
  - docker push thotesonali6/multi-nginx
  - docker push thotesonali6/multi-server
  - docker push thotesonali6/multi-worker